# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Pivt
    Domain: pivt.nl
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Atlantis
    Domain: atlantis.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

# ---------------------------------------------------------------------------
# Used to create external peer org MSP secrets. 
# Required to create channels where external peer orgs participate.
# Additionally init.sh script creates empty placeholder MSP folders for convenience.
# It's user's responsibility to copy MSP certificates to created folders.
# ---------------------------------------------------------------------------
ExternalPeerOrgs:
  - Name: Karga
    Domain: aptalkarga.tr
  - Name: Nevergreen
    Domain: nevergreen.nl